plugin: {}

filetype:
  haskell: |
    inoremap <buffer> <C-l> <space>-> 
    setlocal colorcolumn=79 shiftround nojoinspaces
  rust: |
    inoremap <buffer> <C-l> <space>-> 
  plaintex: |
    iabbrev an &
    let g:tex_conceal=""
  tex: |
    iabbrev an &
    let g:tex_conceal=""
    setlocal backspace=indent,eol
  latex: |
    iabbrev an &
    let g:tex_conceal=""
    setlocal backspace=indent,eol
  gitcommit: |
    setlocal spell

# vim: set expandtab ts=2 sw=2 sts=2:
