plugin:

  Yggdroot/indentLine:
    before: |
      let g:indentLine_faster = 1
      let g:indentLine_char = '▏'
      let g:indentLine_bufTypeExclude = ["help", "terminal"]

  itchyny/lightline.vim: {}
  itchyny/vim-gitbranch: {}

  mhinz/vim-signify: {}
  rhysd/committia.vim: {}
  cohama/agit.vim:
    command:
      - Agit
      - AgitFile

  w0ng/vim-hybrid:
    before: |
      let g:hybrid_custom_term_colors=1

  nanotech/jellybeans.vim:
    after: |
      colorscheme jellybeans
      hi Normal guibg=NONE
      hi NonText guibg=NONE



# vim: set expandtab ts=2 sw=2 sts=2:
