plugin:
  # Colorschemes <<<
  nanotech/jellybeans.vim:
    before: |
      let g:jellybeans_overrides= { 'background': {'guibg': 'none' } }
      let g:jellybeans_use_term_italics = 1

  micke/vim-hybrid:
    before: |
      let g:hybrid_transparent = 1

  reedes/vim-colors-pencil: {}
  # >>>

after:
  colorscheme jellybeans

filetype:
  haskell: |
    inoremap <buffer> <C-l> <space>-> 
    setlocal colorcolumn=79 shiftround nojoinspaces
  rust: |
    inoremap <buffer> <C-l> <space>-> 
  plaintex: |
    iabbrev an &
    let g:tex_conceal=""
  tex: |
    iabbrev an &
    let g:tex_conceal=""
    setlocal backspace=indent,eol
  latex: |
    iabbrev an &
    let g:tex_conceal=""
    setlocal backspace=indent,eol
  gitcommit: |
    setlocal spell

# vim: set expandtab ts=2 sw=2 sts=2 fdm=marker fmr=<<<,>>> fdl=5:
