plugin:
  w0ng/vim-hybrid:
    before: |
      let g:hybrid_custom_term_colors=1
    after: |
      set bg=dark
      colorscheme hybrid

  Yggdroot/indentLine:
    before: |
      let g:indentLine_faster = 1
      let g:indentLine_char = '▏'
      let g:indentLine_bufTypeExclude = ["help", "terminal"]

  itchyny/lightline.vim: {}
  itchyny/vim-gitbranch: {}




# vim: set expandtab ts=2 sw=2 sts=2:
