plugin:

  Shougo/deoplete.nvim:
    dependon:
      - roxma/nvim-yarp
      - roxma/vim-hug-neovim-rpc
    before: |
      let g:deoplete#enable_at_startup=1
      let g:deoplete#enable_smart_case=1
      let g:deoplete#auto_completion_start_length = 2
      let g:deoplete#max_menu_width = 0
    after: |
      set completeopt-=preview
      inoremap <silent><expr> <TAB> pumvisible() ? "\<C-n>" : <SID>check_back_space()
         \  ? "\<TAB>" : deoplete#mappings#manual_complete()
      function! s:check_back_space() abort
        let col = col('.') - 1
        return !col || getline('.')[col - 1]  =~ '\s'
      endfunction
      inoremap <expr><C-h> deoplete#smart_close_popup()."\<C-h>"
      inoremap <expr><BS> deoplete#smart_close_popup()."\<C-h>"
      call deoplete#custom#var('omni', 'input_patterns', {
        \ 'haskell' : '[A-Z][a-z]*\.\w*\|import.*',
        \ 'python' : '\%([^. \t]\.\|^\s*@\|^\s*from\s.\+import \|^\s*from \|^\s*import \)\w*',
        \ 'cpp' :  '[^.[:digit:] *\t]\%(\.\|->\)\|\h\w*::',
        \ } )

  roxma/nvim-yarp:
    dependedby:
      - Shougo/deoplete.nvim
  roxma/vim-hug-neovim-rpc:
    dependedby:
      - Shougo/deoplete.nvim

  w0rp/ale:
    filetype:
      - rust
      - haskell
      - bash
      - c
      - cpp
      - clojure
      - javascript
      - python
      - ruby
    before: |
      let g:ale_rust_cargo_use_clippy = executable('cargo-clippy')
      let g:ale_lint_on_enter = 0
      let g:ale_lint_on_filetype_changed = 0
      let g:ale_lint_on_text_changed = 'never'
      let g:ale_lint_on_save = 0
      let g:ale_open_list = 1
      let g:ale_set_highlights = 0
    after: |
      nmap <silent> <Space>q <Plug>(ale_lint)

  racer-rust/vim-racer:
    filetype: rust
    before: |
      let g:racer_experimental_completer = 1

  rust-lang/rust.vim:
    filetype: rust
    before: |
      let g:rustfmt_autosave=1

  thinca/vim-quickrun:
    command: QuickRun
    before: |
      let g:quickrun_no_default_key_mappings=1
      let g:quickrun_config = {}
      let g:quickrun_config["_"] = {"runner":'job', "hook/dots/enable":1}
      if executable('ikarus')
          let g:quickrun_config.scheme = {'command' : 'ikarus'}
      elseif executable('guile')
          let g:quickrun_config.scheme = {'command' : 'guile'}
      endif
      let g:quickrun_config['haskell/cabal'] =
          \ {'command' : 'cabal', 'cmdopt' : 'exec runghc'}
      let g:quickrun_config['haskell/stack'] =
          \ {'command' : 'stack', 'cmdopt' : 'runghc'}
      let g:quickrun_config.haskell = {'type': 'haskell/stack'}
    after: |
      command! Q QuickRun

  osyo-manga/vim-anzu:
    after: |
      nmap n <Plug>(anzu-n-with-echo)zv
      nmap N <Plug>(anzu-N-with-echo)zv
      nmap * <Plug>(anzu-star-with-echo)N
      nmap # <Plug>(anzu-sharp-with-echo)

  Yggdroot/indentLine:
    before: |
      let g:indentLine_faster = 1
      let g:indentLine_char = '▏'
      let g:indentLine_bufTypeExclude = ["help", "terminal"]

  itchyny/lightline.vim:
    before: |
      let g:lightline = {}
      let g:lightline.colorscheme = 'jellybeans'
      let g:lightline.active = {}
      let g:lightline.active.left = [
        \ ['mode', 'paste'],
        \ ['relativepath',  'modified', 'readonly', 'myFiletype', 'gitbranch', 'curdir'],
        \ [ 'bufnum']
        \ ]
      let g:lightline.active.right = [
        \ [ 'myLineInfo' ],
        \ [ 'percent' ],
        \ [ 'fileencoding' ]
        \ ]
      let g:lightline.inactive = {}
      let g:lightline.inactive.left = [  ['filename', 'modified'] ]
      let g:lightline.component = { 'bufnum': '%([%n]%)',
        \ 'myFiletype': '%{&ft}',
        \ 'myLineInfo' :  '%03l/%03L:%-2v',
        \ 'curdir' : "%<%{fnamemodify(getcwd(),':~')}"
        \ }
      let g:lightline.component_type = { 'bufnum': 'raw', 'gitbranch': 'raw' , 'myFiletype': 'raw'}
      let g:lightline.component_visible_condition = {'myFiletype': '&ft !=# ""' }
      let g:lightline.component_function = {
        \ 'gitbranch' : 'gitbranch#name',
        \ }
      let g:lightline.mode_map = {
        \ 'n' : 'N',  'i' : 'I',  'R' : 'R',  'v' : 'v', 'V' : 'V',
        \ "\<C-v>": 'V-B', 'c' : 'C', 's' : 'S', 'S' : 'S-l',
        \ "\<C-s>": 'S-B', 't': 'TERMINAL' }
  itchyny/vim-gitbranch:
    dependedby: itchyny/lightline.vim

  ctrlpvim/ctrlp.vim:
    before: |
      if executable('files')
          let g:ctrlp_user_command = 'files -i="^(target|\\.git|\\.hg|\\.svn|\\.stack-work|\\.cabal-sandbox|\\..*\.sw.)$" -a %s '
      endif
      let g:ctrlp_follow_symlinks=2
      let g:ctrlp_switch_buffer='Et'
      let g:ctrlp_custom_ignore = {}
      let g:ctrlp_custom_ignore.file = '\v\.(hi|o|out|jsmod|vo|v\.d|glob|pyc)$'
      let g:ctrlp_custom_ignore.dir = '\v[\/]\.(git|hg|svn|stack-work)$'
      if !exists('g:ctrlp_extensions')
          let g:ctrlp_extensions = []
      endif

  ctrlpvim/ctrlp.vim:
    before: |
      if executable('files')
          let g:ctrlp_user_command = 'files -i="^(\\.git|\\.hg|\\.svn|\\.stack-work|\\.cabal-sandbox|\\..*\.sw.)$" -a %s '
      endif
      let g:ctrlp_follow_symlinks=2
      let g:ctrlp_switch_buffer='Et'
      let g:ctrlp_custom_ignore = {}
      let g:ctrlp_custom_ignore.file = '\v\.(hi|o|out|jsmod|vo|v\.d|glob|pyc)$'
      let g:ctrlp_custom_ignore.dir = '\v[\/]\.(git|hg|svn|stack-work)$'
      if !exists('g:ctrlp_extensions')
          let g:ctrlp_extensions = []
      endif

  mattn/ctrlp-register:
    dependon: ctrlpvim/ctrlp.vim
    before: |
      let g:ctrlp_extensions+=['register']
    command: CtrlPRegister
    script: |
      nnoremap <Leader><C-r> :<C-u>CtrlPRegister<CR>

  mattn/ctrlp-mark:
    dependon: ctrlpvim/ctrlp.vim
    before: |
      let g:ctrlp_extensions+=['mark']
    command: CtrlPMark
    script: |
      nnoremap <Leader>m :<C-u>CtrlPMark<CR

  tyru/capture.vim:
    command: Capture

  tyru/caw.vim:
    dependon: kana/vim-repeat
    after: |
      nmap <Leader>c <Plug>(caw:hatpos:toggle)
      vmap <Leader>c <Plug>(caw:hatpos:toggle)


  kana/vim-textobj-user: {}

  thinca/vim-textobj-between:
    dependon: kana/vim-textobj-user
    mapmode:
      - o
      - v
    mapping:
      - af
      - <Plug>(textobj-between-a)
      - if
      - <Plug>(textobj-between-i)
  kana/vim-textobj-indent:
    dependon: kana/vim-textobj-user
    mapmode:
      - o
      - v
    mapping:
      - <Plug>(textobj-indent-a)
      - ai
      - <Plug>(textobj-indent-i)
      - ii
      - <Plug>(textobj-indent-same-a)
      - aI
      - <Plug>(textobj-indent-same-i)
      - iI
  sgur/vim-textobj-parameter:
    dependon: kana/vim-textobj-user
    before: |
      let g:vim_textobj_parameter_mapping = '.'
    mapmode:
      - o
      - v
    mapping:
      - i.
      - a.
  h1mesuke/textobj-wiw:
    dependon: kana/vim-textobj-user
    mapmode:
      - o
      - v
    mapping:
      - a,w
      - i,w
  kana/vim-repeat: {}


  mhinz/vim-signify: {}

  rhysd/committia.vim:
    before: |
      let g:committia_min_window_width = 120

  cohama/agit.vim:
    command:
      - Agit
      - AgitFile

  w0ng/vim-hybrid:
    before: |
      let g:hybrid_custom_term_colors=1

  nanotech/jellybeans.vim:
    after: |
      colorscheme jellybeans
      hi Normal guibg=NONE
      hi NonText guibg=NONE

# vim: set expandtab ts=2 sw=2 sts=2:
